name: finalproject
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  animated_custom_dropdown: ^3.1.1
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.3.1
  chatview: ^2.1.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  dio_http2_adapter: ^2.5.3
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  http_parser: ^4.0.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  introduction_screen: ^3.1.14
  json_theme: ^6.5.0+1
  lottie: ^3.1.2
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/images/
    - assets/images/manual/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica-neue-regular.ttf